services:
  redis:
  image: redis:7-alpine
  restart: always
  volumes:
    - redis_data:/data
  healthcheck:
    test: ["CMD", "redis-cli", "ping"]
    interval: 5s
    timeout: 3s
    retries: 5

  api:
    image: 570515227076.dkr.ecr.ap-southeast-3.amazonaws.com/nutrivision-api:latest
    ports:
      - "8000:8000"
    env_file:
      - ../apps/api/.env
    environment:
      - REDIS_HOST=redis
      - APP_ENV=development
    depends_on:
      - redis
    restart: unless-stopped
