"use client";

import { useState, type FormEvent } from "react";
import { ProtectedRoute } from "@/components/ProtectedRoute";
import { useAuth } from "@/components/AuthProvider";
import { api, ApiError } from "@/lib/api-client";
import type { ActivityLevel, DailyTarget, Gender, Goal } from "@/lib/types";

function ProfileContent() { const { user } = useAuth(); const [gender, setGender] = useState<Gender>("male"); const [age, setAge] = useState(25); const [heightCm, setHeightCm] = useState(170); const [weightKg, setWeightKg] = useState(65); const [activityLevel, setActivityLevel] = useState<ActivityLevel>("moderate"); const [goal, setGoal] = useState<Goal>("maintenance"); const [target, setTarget] = useState<DailyTarget | null>(null); const [saving, setSaving] = useState(false); const [error, setError] = useState<string | null>(null);
  async function handleSubmit(e: FormEvent) { e.preventDefault(); if (!user) return; setSaving(true); setError(null); try { setTarget(await api.saveProfile({ uid: user.uid, gender, age, height_cm: heightCm, weight_kg: weightKg, activity_level: activityLevel, goal })); } catch (err) { setError(err instanceof ApiError ? err.message : "Gagal menyimpan profile."); } finally { setSaving(false); } }
  return <main className="page-shell"><div className="page-container"><p className="eyebrow">Make it personal</p><h1 className="page-title">Profil & target.</h1><p className="lede">Tell us a little about yourself so your daily nutrition targets feel like yours.</p><div className="profile-grid"><section className="card profile-card"><form onSubmit={handleSubmit} className="profile-form"><label className="field-label">Gender<select className="field" value={gender} onChange={(e) => setGender(e.target.value as Gender)}><option value="male">Pria</option><option value="female">Wanita</option></select></label><label className="field-label">Umur (tahun)<input className="field" type="number" min={10} max={100} value={age} onChange={(e) => setAge(Number(e.target.value))} /></label><label className="field-label">Tinggi (cm)<input className="field" type="number" min={1} value={heightCm} onChange={(e) => setHeightCm(Number(e.target.value))} /></label><label className="field-label">Berat (kg)<input className="field" type="number" min={1} value={weightKg} onChange={(e) => setWeightKg(Number(e.target.value))} /></label><label className="field-label full">Level aktivitas<select className="field" value={activityLevel} onChange={(e) => setActivityLevel(e.target.value as ActivityLevel)}><option value="sedentary">Jarang olahraga</option><option value="light">Ringan (1–3x/minggu)</option><option value="moderate">Sedang (3–5x/minggu)</option><option value="active">Aktif (6–7x/minggu)</option><option value="very_active">Sangat aktif</option></select></label><label className="field-label full">Fokus saat ini<select className="field" value={goal} onChange={(e) => setGoal(e.target.value as Goal)}><option value="cutting">Cutting</option><option value="maintenance">Maintenance</option><option value="bulking">Bulking</option></select></label>{error && <div className="alert-error full">{error}</div>}<button type="submit" disabled={saving} className="btn-primary full">{saving ? "Menghitung..." : "Simpan & hitung target"}</button></form></section><aside className="card target-card">{target ? <><p className="eyebrow">Your daily target</p><div className="target-number">{target.calories} <span style={{ fontSize: 14, letterSpacing: 0 }}>kkal</span></div><div className="target-row"><span>Protein</span><strong>{target.protein_g} g</strong></div><div className="target-row"><span>Karbohidrat</span><strong>{target.carbs_g} g</strong></div><div className="target-row"><span>Lemak</span><strong>{target.fat_g} g</strong></div></> : <><p className="eyebrow">Your target</p><h2 style={{ margin: "12px 0", fontSize: 25, letterSpacing: "-.04em" }}>A clearer number to aim for.</h2><p className="lede" style={{ color: "#52675a" }}>Isi profil di samping. Kami akan menghitung target kalori dan makro berdasarkan tubuh, aktivitas, dan fokusmu.</p></>}</aside></div></div></main>; }
export default function ProfilePage() { return <ProtectedRoute><ProfileContent /></ProtectedRoute>; }
